
version: '3'
services:
  User:
    container_name: user
    image: userimage
    build: ./User
    ports:
      - "8000:8000"
  Auth:
    container_name: auth
    image: authimage
    build: ./Authentication
    ports:
      - "8001:8000"
  Notifications:
    container_name: notifications
    image: notificationsimage
    build: ./Notifications
    ports:
      - "8002:8000"

# version: '3'
# services:
#   fooservice:
#     container_name: fooservicecontainer
#     image: fooimage
#     build: ./foo-service
#     ports:
#       - "9000:9000"
#   barservice:
#     container_name: barservicontainer
#     image: barimage
#     build: ./bar-service
#     ports:
#       - "9001:9000"
#   dbservice:
#     container_name: mongodbservicecontainer
#     image: mongo
#     ports:
#       - "27020:27017"
#   redis:
#     container_name: redisservicecontainer
#     image: redis
#     ports:
#       - "9379:6379"
#   nginx:
#     container_name: nginxservicecontainer
#     image: nginx:alpine
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./nginx/public:/srv/www/static
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - fooservice
#       - barservice  